//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreCrime
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PreCrimeEntities : DbContext
    {
        public PreCrimeEntities()
            : base("name=PreCrimeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DIM_GRUPO_OBJETOS> DIM_GRUPO_OBJETOS { get; set; }
        public virtual DbSet<DIM_LOCALIDADE> DIM_LOCALIDADE { get; set; }
        public virtual DbSet<DIM_OBJETOS_FURTADOS> DIM_OBJETOS_FURTADOS { get; set; }
        public virtual DbSet<DIM_TEMPO> DIM_TEMPO { get; set; }
        public virtual DbSet<DIM_TIPO_CRIME> DIM_TIPO_CRIME { get; set; }
        public virtual DbSet<FATO_CADASTRO_CRIME> FATO_CADASTRO_CRIME { get; set; }
        public virtual DbSet<TB_CIDADE> TB_CIDADE { get; set; }
        public virtual DbSet<TB_CONFIGURACAO> TB_CONFIGURACAO { get; set; }
        public virtual DbSet<TB_ESTADO> TB_ESTADO { get; set; }
        public virtual DbSet<TB_ESTATISTICAS> TB_ESTATISTICAS { get; set; }
        public virtual DbSet<TB_OCORRENCIA> TB_OCORRENCIA { get; set; }
        public virtual DbSet<TB_TIPO_CRIME> TB_TIPO_CRIME { get; set; }
        public virtual DbSet<TB_TIPO_OBJETO> TB_TIPO_OBJETO { get; set; }
        public virtual DbSet<TB_TIPO_OBJETO_OCORRENCIA> TB_TIPO_OBJETO_OCORRENCIA { get; set; }
        public virtual DbSet<TB_USUARIO> TB_USUARIO { get; set; }
        public virtual DbSet<FATO_CRIME_LOCALIDADE> FATO_CRIME_LOCALIDADE { get; set; }
        public virtual DbSet<TB_AUX_LOCALIDADE> TB_AUX_LOCALIDADE { get; set; }
        public virtual DbSet<TB_AUX_OCORRENCIA> TB_AUX_OCORRENCIA { get; set; }
        public virtual DbSet<TB_AUX_OCORRENCIA_OBJETOS> TB_AUX_OCORRENCIA_OBJETOS { get; set; }
        public virtual DbSet<TB_AUX_TIPO_DE_CRIME> TB_AUX_TIPO_DE_CRIME { get; set; }
        public virtual DbSet<TB_AUX_TIPO_OBJETOS> TB_AUX_TIPO_OBJETOS { get; set; }
        public virtual DbSet<TB_VIOLACAO_LOCALIDADE> TB_VIOLACAO_LOCALIDADE { get; set; }
        public virtual DbSet<TB_VIOLACAO_OCORRENCIA> TB_VIOLACAO_OCORRENCIA { get; set; }
        public virtual DbSet<TB_VIOLACAO_OCORRENCIA_OBJETOS> TB_VIOLACAO_OCORRENCIA_OBJETOS { get; set; }
        public virtual DbSet<TB_VIOLACAO_TIPO_CRIME> TB_VIOLACAO_TIPO_CRIME { get; set; }
        public virtual DbSet<TB_VIOLACAO_TIPO_OBJETOS> TB_VIOLACAO_TIPO_OBJETOS { get; set; }
    
        public virtual int INSERT_TB_OCORRENCIA(Nullable<System.DateTime> dT_INICIAL, Nullable<System.DateTime> dT_FINAL)
        {
            var dT_INICIALParameter = dT_INICIAL.HasValue ?
                new ObjectParameter("DT_INICIAL", dT_INICIAL) :
                new ObjectParameter("DT_INICIAL", typeof(System.DateTime));
    
            var dT_FINALParameter = dT_FINAL.HasValue ?
                new ObjectParameter("DT_FINAL", dT_FINAL) :
                new ObjectParameter("DT_FINAL", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_TB_OCORRENCIA", dT_INICIALParameter, dT_FINALParameter);
        }
    
        public virtual int PRO_AGREGADO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRO_AGREGADO");
        }
    
        public virtual int PROCEDURE_DIM_LOCALIDADE(Nullable<System.DateTime> dATACARGA)
        {
            var dATACARGAParameter = dATACARGA.HasValue ?
                new ObjectParameter("DATACARGA", dATACARGA) :
                new ObjectParameter("DATACARGA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROCEDURE_DIM_LOCALIDADE", dATACARGAParameter);
        }
    
        public virtual int PROCEDURE_DIM_OBJETOS_FURTADOS(Nullable<System.DateTime> dATACARGA)
        {
            var dATACARGAParameter = dATACARGA.HasValue ?
                new ObjectParameter("DATACARGA", dATACARGA) :
                new ObjectParameter("DATACARGA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROCEDURE_DIM_OBJETOS_FURTADOS", dATACARGAParameter);
        }
    
        public virtual int PROCEDURE_DIM_TIPO_CRIME(Nullable<System.DateTime> dATACARGA)
        {
            var dATACARGAParameter = dATACARGA.HasValue ?
                new ObjectParameter("DATACARGA", dATACARGA) :
                new ObjectParameter("DATACARGA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROCEDURE_DIM_TIPO_CRIME", dATACARGAParameter);
        }
    
        public virtual int PROCEDURE_GRUPO_OBJETOS(Nullable<System.DateTime> dATACARGA)
        {
            var dATACARGAParameter = dATACARGA.HasValue ?
                new ObjectParameter("DATACARGA", dATACARGA) :
                new ObjectParameter("DATACARGA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROCEDURE_GRUPO_OBJETOS", dATACARGAParameter);
        }
    
        public virtual int SP_DIM_TEMPO(Nullable<System.DateTime> dATAINICIO, Nullable<System.DateTime> dATAFIM)
        {
            var dATAINICIOParameter = dATAINICIO.HasValue ?
                new ObjectParameter("DATAINICIO", dATAINICIO) :
                new ObjectParameter("DATAINICIO", typeof(System.DateTime));
    
            var dATAFIMParameter = dATAFIM.HasValue ?
                new ObjectParameter("DATAFIM", dATAFIM) :
                new ObjectParameter("DATAFIM", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DIM_TEMPO", dATAINICIOParameter, dATAFIMParameter);
        }
    
        public virtual int SP_FATO_CADASTRAR(Nullable<System.DateTime> dATACARGA)
        {
            var dATACARGAParameter = dATACARGA.HasValue ?
                new ObjectParameter("DATACARGA", dATACARGA) :
                new ObjectParameter("DATACARGA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_FATO_CADASTRAR", dATACARGAParameter);
        }
    
        public virtual int SP_OLTP_LOCALIDADE(Nullable<System.DateTime> dATACARGA)
        {
            var dATACARGAParameter = dATACARGA.HasValue ?
                new ObjectParameter("DATACARGA", dATACARGA) :
                new ObjectParameter("DATACARGA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OLTP_LOCALIDADE", dATACARGAParameter);
        }
    
        public virtual int SP_OLTP_OCORRENCIA(Nullable<System.DateTime> dATACARGA)
        {
            var dATACARGAParameter = dATACARGA.HasValue ?
                new ObjectParameter("DATACARGA", dATACARGA) :
                new ObjectParameter("DATACARGA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OLTP_OCORRENCIA", dATACARGAParameter);
        }
    
        public virtual int SP_OLTP_OCORRENCIA_TIPO_OBJETO(Nullable<System.DateTime> dATACARGA)
        {
            var dATACARGAParameter = dATACARGA.HasValue ?
                new ObjectParameter("DATACARGA", dATACARGA) :
                new ObjectParameter("DATACARGA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OLTP_OCORRENCIA_TIPO_OBJETO", dATACARGAParameter);
        }
    
        public virtual int SP_OLTP_TIPO_CRIME(Nullable<System.DateTime> dATACARGA)
        {
            var dATACARGAParameter = dATACARGA.HasValue ?
                new ObjectParameter("DATACARGA", dATACARGA) :
                new ObjectParameter("DATACARGA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OLTP_TIPO_CRIME", dATACARGAParameter);
        }
    
        public virtual int SP_OLTP_TIPO_OBJETO(Nullable<System.DateTime> dATACARGA)
        {
            var dATACARGAParameter = dATACARGA.HasValue ?
                new ObjectParameter("DATACARGA", dATACARGA) :
                new ObjectParameter("DATACARGA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OLTP_TIPO_OBJETO", dATACARGAParameter);
        }
    }
}
