//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreCrime
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIM_TIPO_CRIME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIM_TIPO_CRIME()
        {
            this.FATO_CADASTRO_CRIME = new HashSet<FATO_CADASTRO_CRIME>();
        }
    
        public int ID_TIPO_CRIME { get; set; }
        public Nullable<int> COD_TIPO_CRIME { get; set; }
        public string TIPO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FATO_CADASTRO_CRIME> FATO_CADASTRO_CRIME { get; set; }
    }
}
