//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreCrime
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIM_OBJETOS_FURTADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIM_OBJETOS_FURTADOS()
        {
            this.DIM_GRUPO_OBJETOS = new HashSet<DIM_GRUPO_OBJETOS>();
        }
    
        public int ID_OBJETOS_FURTADOS { get; set; }
        public Nullable<int> COD_OBJETOS_FURTADOS { get; set; }
        public string TIPO_OBJETO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIM_GRUPO_OBJETOS> DIM_GRUPO_OBJETOS { get; set; }
    }
}
