//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreCrime
{
    using System;
    using System.Collections.Generic;
    
    public partial class FATO_CRIME_LOCALIDADE
    {
        public int ID_LOCALIDADE { get; set; }
        public int QUANTIDADE { get; set; }
    }
}
