//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreCrime
{
    using System;
    using System.Collections.Generic;
    
    public partial class FATO_CADASTRO_CRIME
    {
        public int ID_CADASTRO_CRIME { get; set; }
        public int ID_TEMPO { get; set; }
        public int ID_TIPO_CRIME { get; set; }
        public int ID_OCALIDADE { get; set; }
        public int QUANTIDADE { get; set; }
        public decimal PREJUIZO { get; set; }
        public string DESCRICAO_CRIME { get; set; }
    
        public virtual DIM_LOCALIDADE DIM_LOCALIDADE { get; set; }
        public virtual DIM_TEMPO DIM_TEMPO { get; set; }
        public virtual DIM_TIPO_CRIME DIM_TIPO_CRIME { get; set; }
    }
}
