//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreCrime
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AUX_TIPO_OBJETOS
    {
        public System.DateTime DATA_CARGA { get; set; }
        public int COD_TIPO_OBJETOS { get; set; }
        public string TIPO_OBJETO { get; set; }
    }
}
