//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreCrime
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AUX_OCORRENCIA
    {
        public System.DateTime DATA_CARGA { get; set; }
        public int COD_OCORRENCIA { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public Nullable<int> LATITUDE { get; set; }
        public Nullable<int> LONGITUDE { get; set; }
        public string DESCRICAO_OCORRENCIA { get; set; }
        public Nullable<System.DateTime> HORA { get; set; }
        public Nullable<decimal> PREJUIZO { get; set; }
        public Nullable<int> COD_USUARIO { get; set; }
        public Nullable<int> COD_TIPO_CRIME { get; set; }
        public Nullable<int> COD_CIDADE { get; set; }
    }
}
