//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreCrime
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CIDADE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CIDADE()
        {
            this.TB_ESTATISTICAS = new HashSet<TB_ESTATISTICAS>();
            this.TB_OCORRENCIA = new HashSet<TB_OCORRENCIA>();
        }
    
        public int COD_CIDADE { get; set; }
        public string CIDADE { get; set; }
        public Nullable<int> LATITUDE { get; set; }
        public Nullable<int> LONGITUDE { get; set; }
        public int COD_ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ESTATISTICAS> TB_ESTATISTICAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_OCORRENCIA> TB_OCORRENCIA { get; set; }
        public virtual TB_ESTADO TB_ESTADO { get; set; }
    }
}
