//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreCrime
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ESTATISTICAS
    {
        public int COD_ESTATISTICA { get; set; }
        public Nullable<decimal> PERCENTUAL_CRIME { get; set; }
        public Nullable<int> QUANTIDADE_CRIME { get; set; }
        public Nullable<decimal> HORARIO_CRIME { get; set; }
        public int COD_CIDADE { get; set; }
        public int COD_TIPO_CRIME { get; set; }
    
        public virtual TB_CIDADE TB_CIDADE { get; set; }
    }
}
