//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreCrime
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ESTADO
    {
        public int COD_ESTADO { get; set; }
        public string ESTADO { get; set; }
    
        public virtual TB_CIDADE TB_CIDADE { get; set; }
    }
}
