//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreCrime
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_OCORRENCIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_OCORRENCIA()
        {
            this.TB_TIPO_OBJETO_OCORRENCIA = new HashSet<TB_TIPO_OBJETO_OCORRENCIA>();
        }
    
        public int COD_OCORRENCIA { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public Nullable<int> LATITUDE { get; set; }
        public Nullable<int> LONGITUDE { get; set; }
        public string DESCRICAO_OCORRENCIA { get; set; }
        public Nullable<System.DateTime> HORA { get; set; }
        public Nullable<decimal> PREJUIZO { get; set; }
        public int COD_USUARIO { get; set; }
        public int COD_TIPO_CRIME { get; set; }
        public int COD_CIDADE { get; set; }
    
        public virtual TB_CIDADE TB_CIDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TIPO_OBJETO_OCORRENCIA> TB_TIPO_OBJETO_OCORRENCIA { get; set; }
        public virtual TB_TIPO_CRIME TB_TIPO_CRIME { get; set; }
        public virtual TB_USUARIO TB_USUARIO { get; set; }
    }
}
