//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreCrime
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TIPO_OBJETO_OCORRENCIA
    {
        public int COD_TIPO_ODJETO_OCORRENCIA { get; set; }
        public string DECRICAO_TIPO_OBJETO_OCORRENCIA { get; set; }
        public int COD_TIPO_OBJETO { get; set; }
        public int COD_OCORRENCIA { get; set; }
    
        public virtual TB_OCORRENCIA TB_OCORRENCIA { get; set; }
        public virtual TB_TIPO_OBJETO TB_TIPO_OBJETO { get; set; }
    }
}
