//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreCrime
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_USUARIO()
        {
            this.TB_CONFIGURACAO = new HashSet<TB_CONFIGURACAO>();
            this.TB_OCORRENCIA = new HashSet<TB_OCORRENCIA>();
        }
    
        public int COD_USUARIO { get; set; }
        public string EMAIL { get; set; }
        public string SENHA { get; set; }
        public string CIDADE { get; set; }
        public string ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CONFIGURACAO> TB_CONFIGURACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_OCORRENCIA> TB_OCORRENCIA { get; set; }
    }
}
