//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreCrime
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_VIOLACAO_OCORRENCIA
    {
        public Nullable<System.DateTime> DATA_CARGA { get; set; }
        public Nullable<int> ID_TEMPO { get; set; }
        public Nullable<int> ID_TIPO_CRIME { get; set; }
        public Nullable<int> ID_OCALIDADE { get; set; }
        public Nullable<int> QUANTIDADE { get; set; }
        public Nullable<decimal> PREJUIZO { get; set; }
        public string DESCRICAO_CRIME { get; set; }
        public System.DateTime DATA_VIOLACAO { get; set; }
        public string DESCRICAO_VIOLACAO { get; set; }
    }
}
