//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreCrime
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_VIOLACAO_LOCALIDADE
    {
        public System.DateTime DATA_CARGA { get; set; }
        public Nullable<int> COD_CIDADE { get; set; }
        public string CIDADE { get; set; }
        public string ESTADO { get; set; }
        public Nullable<int> LATITUDE { get; set; }
        public Nullable<int> LONGITUDE { get; set; }
        public System.DateTime DATA_VIOLACAO { get; set; }
        public string DESCRICAO_VIOLACAO { get; set; }
    }
}
