//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreCrime
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_VIOLACAO_OCORRENCIA_OBJETOS
    {
        public System.DateTime DATA_CARGA { get; set; }
        public Nullable<int> COD_OCORRENCIA_OBJETO { get; set; }
        public Nullable<int> COD_TIPO_OBJETO { get; set; }
        public string DECRICAO_TIPO_OBJETO_OCORRENCIA { get; set; }
        public System.DateTime DATA_VIOLACAO { get; set; }
        public string DESCRICAO_VIOLACAO { get; set; }
    }
}
